root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/main.exe"
cmd = "go build -o ./tmp/main.exe ./cmd"
include_ext = ["go", "tpl", "tmpl", "html"]

[watch]
extensions = ["go", "tpl", "js", "html", "toml"]

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[screen]
clear_on_rebuild = false
keep_scroll = true
