app_name = "realtime-message-push-service"
env = "development"                        # development | production

[server]
address = "0.0.0.0"
port = 8080

[redis.session]
addr = "127.0.0.1:6379"
db = 0
pool_size = 50

[redis.message]
addr = "127.0.0.1:6380"
db = 0
pool_size = 100

[jwt]
secret = "replace_with_secure_secret"
issuer = "rtmp-push"
token_prefix = "Bearer "
access_exp_minutes = 60
refresh_exp_hours = 24
