version: "3.9"

services:
  redis-session:
    image: redis:7-alpine
    container_name: redis-session
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]

  redis-message:
    image: redis:7-alpine
    container_name: redis-message
    ports:
      - "6380:6379"
    command: [ "redis-server", "--appendonly", "yes" ]

  zookeeper:
    image: confluentinc/cp-zookeeper:8.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:8.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
