// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/Gopher0727/RTMP/config"
	"github.com/Gopher0727/RTMP/internal/api"
	"github.com/Gopher0727/RTMP/internal/repository"
	"github.com/Gopher0727/RTMP/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitApp 初始化应用依赖
func InitApp(db *gorm.DB) (*App, error) {
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	messageRepository := repository.NewMessageRepository(db)
	roomRepository := repository.NewRoomRepository(db)

	messageService := service.NewMessageService(messageRepository, roomRepository)
	roomService := service.NewRoomService(roomRepository)
	hubService := service.NewHubService(userRepository, messageRepository, roomRepository, db)
	authHandler := api.NewAuthHandler(userService)
	userHandler := api.NewUserHandler(userService)
	messageHandler := api.NewMessageHandler(messageService)
	roomHandler := api.NewRoomHandler(roomService)
	config := _wireConfigValue
	app := NewApp(userService, messageService, roomService, hubService, authHandler, userHandler, messageHandler, roomHandler, config)
	return app, nil
}

var (
	_wireConfigValue = &config.Config{}
)

// wire.go:

// App 应用结构体
type App struct {
	// 服务层
	UserService    service.UserService
	MessageService service.MessageService
	RoomService    service.RoomService
	HubService     service.HubService

	// API处理器层
	AuthHandler    *api.AuthHandler
	UserHandler    *api.UserHandler
	MessageHandler *api.MessageHandler
	RoomHandler    *api.RoomHandler

	// 配置
	Config *config.Config
}

// NewApp 创建应用
func NewApp(
	userService service.UserService,
	messageService service.MessageService,
	roomService service.RoomService,
	hubService service.HubService,
	authHandler *api.AuthHandler,
	userHandler *api.UserHandler,
	messageHandler *api.MessageHandler,
	roomHandler *api.RoomHandler, config2 *config.Config,
) *App {
	return &App{
		UserService:    userService,
		MessageService: messageService,
		RoomService:    roomService,
		HubService:     hubService,
		AuthHandler:    authHandler,
		UserHandler:    userHandler,
		MessageHandler: messageHandler,
		RoomHandler:    roomHandler,
		Config:         config2,
	}
}
